### ISSUE TITLE
Where are drawings stored?

### ISSUE THREAD

**Issue by gbernal** [NYUCCL/drawtogether#1]
Hi there,

Thank you for sharing the project. I have been playing with the drawtogether code, but I don't seem to figure out where the images drawn by the user stored are? Also, when I add /gallery to my URL https://sketchcollect.herokuapp.com/ the Art Gallery shows a blank page. Are there any steps missing from the README file?

I would appreciate any help. Thank you.

**Comment by deargle** [comment]
Probably an issue with this repo needing to be updated to work with psiturk v3

**Comment by deargle** [comment]
Since lol the project was last updated 7 years ago. You're using psiturk v3, right?

**Comment by gbernal** [comment]
Thank you for your quick response. Yes, I'm using Psyturk v3

**Comment by deargle** [comment]
You can try the experiment with psiturk v2 -- I bet that will work -- or if you're brave, you can dive in with psiturk v3 and help migrate it.

**Comment by gbernal** [comment]
I would gladly help migrate. I think I have managed to get migrate most of the issues. Although I haven't kept track of the changes, I would have to go back and make sure I don't miss anything. Two blocking items for me at the moment are one figure out where or how to retrieve the data and make sure I can test the hit within the sandbox.

**Comment by deargle** [comment]
I just released 3.1.0 which has a fix for the `download_datafiles` command, if that's what you're referring to. As for testing on sandbox, I run everything on heroku, see here: https://psiturk.readthedocs.io/en/latest/tutorials/heroku.html

**Comment by gbernal** [comment]
I will install the latest version of Psiturk and see if that fixes it.

**Comment by gbernal** [comment]
update help with my original question, I have created a pull request with the changes for V3 compatibility. 
Thank you
